### ISSUE TITLE
Deploy Phlask

### ISSUE THREAD

**Issue by themightychris** [CodeForPhilly/ops#38]
## TODO

- [X] Verify that application can be started locally with `docker-compose up`
- [X] Fill out repository and branch below
- [X] Set up CodeForPhilly.org project profile and add link below
- [X] Record any additional notes, if any

## Deployment specifications

- **Repository:** https://github.com/phlask/phlask-map
- **Branch:** dockerize
- **Project Profile:** https://codeforphilly.org/projects/phlask--life-liberty_and_the_pursuit_of_water

**Comment by gcardonag** [comment]
Hey, just following up on this since we've been working on moving the project to react and have an initial version that can go out. We've since moved to the `develop` branch which can be deployed via `docker-compose up`. Would anything else be needed from our end to deploy?

**Comment by themightychris** [comment]
@gcardonag could you tag a release version? Just create a tag named `v1.0.0` somewhere and we'll start incrementing it. Or use `v0.1.0` if it doesn't feel ready for general public use yet

**Comment by gcardonag** [comment]
Done! v0.1.0 is up: https://github.com/phlask/phlask-map/tree/v0.1.0

**Comment by themightychris** [comment]
@gcardonag We've finally got a beta cluster running, and I've deployed phlask here temporarily: https://phlask.beta-cluster.phl.io/

The deployment is driven by: https://github.com/CodeForPhilly/civic-cluster/blob/master/phlask/manifest.yaml

I noticed you have some new work to do a production build. I recommend that you reconfigure your Dockerfile to always do the production build, and then have dev mode be the overridden command/entrypoint

When you have a Dockerfile that makes a production container by default, tag a new release version and let us know here
