### ISSUE TITLE
Deploy PreventionPoint-Metabase

### ISSUE THREAD

**Issue by mariekers** [CodeForPhilly/ops#39]
## TODO

- [x] Verify that application can be started locally with `docker-compose up`
- [x] Fill out repository and branch below
- [x] Set up CodeForPhilly.org project profile and add link below
- [x] Record any additional notes, if any

## Deployment specifications

- **Repository:** https://github.com/CodeForPhilly/prevpoint-metabase
- **Branch:** master
- **Project Profile:** https://codeforphilly.org/projects/prevention_point_unified_reporting_system
