### ISSUE TITLE
Deploy [APP] PardonsApp

### ISSUE THREAD

**Issue by drexelapplab** [CodeForPhilly/ops#42]
## TODO

- [ ] Verify that application can be started locally with `docker-compose up`
- [ ] Fill out repository and branch below
- [ ] Set up CodeForPhilly.org project profile and add link below
- [ ] Record any additional notes, if any

## Deployment specifications

- **Repository:** https://github.com/drexelapplab/pardonsCFP
- **Branch:** master
- **Project Profile:** https://codeforphilly.org/projects/philadelphia_lawyers_for_social_equity_-_record_expungement

**Comment by themightychris** [comment]
@drexelapplab thanks, this look thoroughly well put together already!

A couple tweaks -- could you set up your root `.gitignore` to exclude the `.DS_Store` files and `node_modules/` directories? (as well as removing all the already-committed ones from source control?)

Since you only have a couple commits at this point, it would be best if you could rebase the commits so that `.gitignore` is in place from the beginning and `node_modules/` never gets into the history, at this point you can easily purge them from the history instead of just deleting them in a newer commit, which will help keep your project cloning and building a lot quicker indefinitely.

**Comment by themightychris** [comment]
@drexelapplab same goes for the `vendor/` directory. Have your Dockerfile handle running `composer install` and `npm install` so that the project source -> deployable container flow is assured to be repeatable outside your machine

We want to be sure that anything we deploy, we have the ability to apply routine dependency updates to without needing to get in touch with any original developers. With your vendor/node_modules libraries versioned like this, we don't know that fresh installs of all the dependencies from what's inside package.json/composer.json will produce working versions. Theoretically (and surprisingly commonly in practice) the functioning of the application will come to depend on manual changes or custom commands run against those directories that only the developer knows about, and requiring that the Dockerfile be handling that forces any exceptions to either be handled within those manifests or within the Dockerfile
