### ISSUE TITLE
Deploy Prevention Point MVP 

### ISSUE THREAD

**Issue by mariekers** [CodeForPhilly/ops#46]
## TODO

- [x] Verify that application can be started locally with `docker-compose up`
- [x] Fill out repository and branch below
- [x] Set up CodeForPhilly.org project profile and add link below
- [x] Record any additional notes, if any

## Deployment specifications

- **Repository:** https://github.com/CodeForPhilly/prevention-point
- **Branch:** master
- **Project Profile:** https://codeforphilly.org/project/prevention_point_unified_reporting_system
- **Tagged Release:** https://github.com/CodeForPhilly/prevention-point/releases/tag/v0.1.0-rc.1

## Additional notes
Should start postgres db, django back end, create and connect front end, then seed postgres with fake data.  

Fake data does not need to persist in future deploys.

**Comment by mariekers** [comment]
This just needs to be a demo instance on linode, similar to the method @machow used to put the [MVP on Digital Ocean ](http://64.225.27.230:8080/)
