### ISSUE TITLE
Deploy CHIME

### ISSUE THREAD

**Issue by mariekers** [CodeForPhilly/ops#47]
## TODO

- [x] Verify that application can be started locally with `docker-compose up`
- [x] Fill out repository and branch below
- [x] Set up CodeForPhilly.org project profile and add link below
- [ ] Record any additional notes, if any

## Deployment specifications

- **Repository:** https://github.com/pennsignals/chime/releases/tag/0.1
- **Branch:** master
- **Project Profile:** https://codeforphilly.org/projects/chime

## Additional notes
Project is currently working on implementing scripts to rule them all
project can be launched using 
```
docker build -t chime
docker run -d -p 80:8000 chime
```

## Deployment progress

- [ ] Document run-flow via STRTA: pennsignals/chime#36
- [ ] Add to civic-cluster: CodeForPhilly/civic-cluster#6
